Step1
lhs0610/kotlin-racingcar pull request #16
Opened 2023-07-23 13:52 UTC by tmddnrdl333

step1 1단계 피드백 반영 및 2단계 구현했습니다.

2023-07-25 02:23 UTC, lhs0610 requested changes
승욱님 2단계 미션 잘 구현해주셨는데, 
- 하나의 클래스에 모든 책임이 다 있어 SRP 원칙에 위배된다. 
- 매직 리터럴이 그대로 하드코딩 되어 유지보수가 힘들다. 

그리고 추가적인 기타 피드백을 남겨드렸으니 확인 후 다시 리뷰요청 부탁드려요.

2023-07-25 02:23 UTC, lhs0610 commented on src/main/kotlin/Calculator.kt
> +    private val list: List<String>
이렇게 변수들을 선언한 이유가 있을까요?

2023-07-25 02:23 UTC, lhs0610 commented on src/main/kotlin/Calculator.kt
> +class Calculator(str: String?) {
계산기가 하나의 문자열마다 새로 생성될 필요가 있을까요? 메서드에서만 문자열을 받아도 될 것 같네요!

2023-07-25 02:23 UTC, lhs0610 commented on src/main/kotlin/Calculator.kt
> +    private fun operate(op: Char?, num2: Int?) {
op와 num2라는 이름은 좀 직관적이지 않은 것 같네요. 좀 더 이름을 명확하게 지을 수 없을까요?
그리고 nullable 타입으로 선언한 이유가 있을까요? 별도의 사유가 있는게 아니라면 non-null 타입으로 하는 걸 권장드립니다.

2023-07-25 02:23 UTC, lhs0610 commented on src/main/kotlin/Calculator.kt
> +        num2 ?: throwIfNoNumber()
require문을 이용해 예외 체킹을 할 수 있어요([link](https://catsbi.oopy.io/2885f744-600e-49ea-a6a8-e321a31df527#05d7fa96-5738-43d1-9d9d-d5e5e4f6ce41))

2023-07-25 02:23 UTC, lhs0610 commented on src/main/kotlin/Calculator.kt
> +            '/' -> num /= num2!!
각 문자열에 대한 연산 책임을 when 절에서 하드코딩으로 직접 하게 될 경우 유지보수성 측면에서 떨어질 수 있어요. 
만약 여기서 제곱이라거나 다른 연산이 추가된다면 이 코드를 수정해야하는데 이 경우, OCP원칙을 위반할 수 있겠죠?
열거타입으로 분리를 해보면 어떨까요

2023-07-25 02:23 UTC, lhs0610 commented on src/main/kotlin/Calculator.kt
> +    }
여기도 위와같이 사칙연산에 대한 하드코등 문제, 인스턴스변수 공유문제등이 있을 것 같네요.

2023-07-25 02:23 UTC, lhs0610 commented on src/main/kotlin/Calculator.kt
> +    }
예외를 던지는 것 뿐인 함수는 어떤 의미가 있을까요?

2023-07-25 02:23 UTC, lhs0610 commented on src/test/kotlin/Test.kt
> +class Test : StringSpec({
0으로 나누거나 0을 나누려는 경우, 공백으로 문자열 분리가 안되있는 경우 연산자가 연달아 있거나 피연산자가 연달아 있는 경우, 맨 앞이나 맨 끝이 피연산자가 아니라 연산자인경우 등에 대한 테스트도 있어야 할 듯 싶네요.

2023-07-25 11:48 UTC, tmddnrdl333 commented on src/main/kotlin/Calculator.kt
> +        num2 ?: throwIfNoNumber()
감사합니다! 다음 커밋에 적용해보았습니다.

2023-07-25 11:49 UTC, tmddnrdl333 commented on src/main/kotlin/Calculator.kt
> +            '/' -> num /= num2!!
다음 커밋에 열거형에서 인터페이스를 구현하는 형식으로 작성해봤습니다!

2023-07-25 11:49 UTC, tmddnrdl333 commented on src/test/kotlin/Test.kt
> +class Test : StringSpec({
다음 커밋에 말씀 주신 엣지 케이스들에 대한 테스트도 작성해봤습니다!

2023-07-25 11:50 UTC, tmddnrdl333 commented on src/main/kotlin/Calculator.kt
> +    private val list: List<String>
자세한 피드백 주셔서 감사합니다!
읽으면서 설계에 구멍이 많은 것 같아서 재설계해서 구현해봤습니다.
감사합니다!

2023-07-26 01:10 UTC, lhs0610 approved these changes
승욱님, 추가적인 패드백 남겨드렸으니 확인 후 다음 미션 진행하시며 같이 반영해보도록 하시죠. 
이만 merge하겠습니다.

2023-07-26 01:10 UTC, lhs0610 commented on src/main/kotlin/component/MathExpression.kt
> +class MathExpression(str: String?) {
- 변수명은 의미있게 지어주세요.  
- 초기화블럭에서 null check해서 예외를 던질꺼면 그냥 여기서 non-null 타입으로 선언하면 되지 않을까요?

2023-07-26 01:10 UTC, lhs0610 commented on src/main/kotlin/component/MathExpression.kt
> +        val list = str.split(" ")
여기는 또 하드코딩을 하셨네요 🤔

2023-07-26 01:10 UTC, lhs0610 commented on src/main/kotlin/component/MathExpression.kt
> +        }
- 반복문안에 분기문이 있어요. 그러다보니 indent가 3이 되는데 어떻게 줄일 수 없을까요? 
- 한 로직에 연산자 추출과 피연산자 추출 로직 두 개를 모두 책임지고 있어요. 분리해보면 어떨까요?  

다음 글을 참고해서 지키도록 해보시죠 ([link](https://catsbi.oopy.io/bf003ff6-2912-4714-8ac2-44eeb7becc93))

2023-07-26 01:10 UTC, lhs0610 commented on src/main/kotlin/component/MathExpression.kt
> +        }
이런 검증역할도 Operator가 알아서 해도 되지 않을까요?

2023-07-26 01:10 UTC, lhs0610 commented on src/main/kotlin/component/MathExpression.kt
> +        require(operatorList.size > 0 && operatorList.size + 1 == numList.size) {
이 메서드를 호출하는 부분이 이미 require인데, 여기서도 require를 쓸 필요가 있을까요?

2023-07-26 01:10 UTC, lhs0610 commented on src/main/kotlin/enums/Operator.kt
> +enum class Operator(val operator: String) : BinaryOperator<Int> {
람다 표현식을 통해 더 간결하게 코드 작성이 가능할 것 같아요.

2023-07-26 01:10 UTC, lhs0610 commented on src/main/kotlin/enums/Operator.kt
> +            return t / u
0을 나누거나 할 때 ArithmeticException이 발생할 것 같네요

2023-07-26 01:10 UTC, lhs0610 commented on src/main/kotlin/enums/Operator.kt
> +        }
원하는 타입이 없을 때 예외를 던지는 것 보다는 NONE과 같이 없다는 결과의 Enum을 만들어 제공하는게 더 나은 선택일 수 있어요

2023-07-26 01:11 UTC, merged

2023-07-26 10:06 UTC, tmddnrdl333 commented on src/main/kotlin/component/MathExpression.kt
> +class MathExpression(str: String?) {
실제로 문자열 계산기를 만든다면 그게 맞을 것 같습니다.
근데 제시문에서 입력 값이 null인 경우도 상정하고 있는 것 같아서 그렇게 구현한 것 같습니다..

다음 커밋에는 참고하여 non-null 로 변경 적용하겠습니다!