2 단계 - 문자열 계산기
lhs0610/kotlin-racingcar pull request #3
Opened 2023-07-10 07:58 UTC by qkrjh0904

2023-07-10 08:10 UTC, lhs0610 requested changes
정호님 2단계 미션 빠르게 진행해주시네요 역시 모범생 💯 
몇 가지 피드백 남겨드렸으니 확인 후 다시 리뷰요청 부탁드려요 👍

2023-07-10 08:10 UTC, lhs0610 commented on src/test/kotlin/PersonTest.kt
>  class PersonTest : FunSpec({
피드백 반영 💯

2023-07-10 08:10 UTC, lhs0610 commented on src/test/kotlin/StringCalculatorTest.kt
> +    }
`require` 제한 블럭을 사용할 수 있을 것 같아요 👍

2023-07-10 08:10 UTC, lhs0610 commented on src/test/kotlin/StringCalculatorTest.kt
> +    val splitExpression = expression.split(" ")
매직 리터럴이 보이네요. 구분자를 상수로 분리할 수 있을 것 같네요.

2023-07-10 08:10 UTC, lhs0610 commented on src/test/kotlin/StringCalculatorTest.kt
> +    var answer = splitExpression[0].toInt()
숫자로 변경할 수 없는 값일 경우에 대한 유효성 검증은 필요 없을까요?

2023-07-10 08:10 UTC, lhs0610 commented on src/test/kotlin/StringCalculatorTest.kt
> +}
중위함수를 사용하신건 좋습니다만, 해당 연산자의 경우 연산자 오버로딩을 활용하는게 더 좋지 않을까요? ([참고](https://jaehhh.tistory.com/93))

연산자 오버로딩을 사용하기 위해서는 일급 객체를 사용해볼 수 있겠네요

2023-07-10 08:10 UTC, lhs0610 commented on src/test/kotlin/StringCalculatorTest.kt
> +            "/" -> answer div number
4개의 한정적인 연산자의 경우 열거타입으로 만들어도 괜찮을 것 같네요. 
또한 열거타입 내부적으로 캐싱을 해서 시간복잡도를 O(1)로 만들어 볼 수도 있을 것 같네요 👍

2023-07-10 08:10 UTC, lhs0610 commented on src/test/kotlin/StringCalculatorTest.kt
> +        val number = splitExpression[index + 1].toInt()
해당 문자가 숫자가 아닐 경우에 대한 대응이 필요해 보이네요!
그리고 +1이 무엇을 의미하는지 매직넘버라서 알기 힘들어 보이네요!

2023-07-10 08:10 UTC, lhs0610 commented on src/test/kotlin/StringCalculatorTest.kt
> +            else -> throw IllegalArgumentException("사칙 연산 기호가 아닙니다.")
예외메시지를 좀 더 친절하게 작성해봐도 좋을 것 같아요. 입력한 메세지가 무엇이기에 사칙 연산 기호가 아니라는지 포함시키면 어떨까요?

2023-07-10 08:10 UTC, lhs0610 commented on src/test/kotlin/StringCalculatorTest.kt
> +
피연산자 위치에 숫자가 아닌 값이 들어가거나, 연산자 위치에 숫자나 다른 문자가 들어갈 경우에 대한 테스트 케이스도 있으면 어떨까요?

2023-07-12 01:22 UTC, lhs0610 approved these changes
정호님 피드백 반영 잘 해주셨어요. 몇 가지 추가 피드백을 남겼는데, 확인하시고 3단계 미션 진행하시면서 같이 고민해보면 좋을 것 같아요 2단계는 여기서 머지하겠습니다.

2023-07-12 01:22 UTC, lhs0610 commented on src/main/kotlin/enums/Operator.kt
> +            throw IllegalArgumentException("${ErrorMessage.NOT_A_OPERATOR.message} operator=$operator")
💯

2023-07-12 01:22 UTC, lhs0610 commented on src/main/kotlin/objects/StringCalculator.kt
> +    private val expression: String?
계산기가 덧셈하나 할 때마다 하나씩 생기는건 좀 이상하지 않을까요 🤔
object클래스로만들어 무상태로 설계할수도 있을 것 같네요!
혹은 인스턴스로 만든다 하더라도 표현식 자체를 생성자 프로퍼티르 받을 필요는 없을 것 같아요!

2023-07-12 01:22 UTC, lhs0610 commented on src/main/kotlin/objects/StringCalculator.kt
> +        }
- 계산기에서 숫자 변환까지 책임지는건 좀 과도한 책임을 지게 되는 것 같기에 이런 경우 Number등을 이용해 일급 값 객체를 만들어 책임을 분리시킬 수 있습니다.
- 해당 예외는 NumberFormatException으로도 충분히 시그니처를 보여줄 수 있기에 IllegalArgumentException으로 예외 번역 및 전파를 하는건 메세지를 추가한다는 것 빼고는 의의를 가지기 힘듭니다. 차라리 toDoubleOrNull을 이용해서 null일 경우에 대한 예외를 IllegalArgumentException으로 던지는게 좀 더 명확하겠죠

2023-07-12 01:22 UTC, lhs0610 commented on src/main/kotlin/enums/Operator.kt
> +    DIV("/");
여기서 각각의 열거타입이 람다식을 가져서 연산을 책임지도록 해도 괜찮을 것 같네요!

2023-07-12 05:22 UTC, merged

2023-07-12 08:38 UTC, qkrjh0904 commented on src/test/kotlin/StringCalculatorTest.kt
> +
예리하시군요!
필요할까 했는데, 실제 서비스 구현한다는 생각으로 해봐야겠네요!

2023-07-12 08:38 UTC, qkrjh0904 commented on src/test/kotlin/StringCalculatorTest.kt
> +    }
또 새로운걸 알아가네요!😀😀

2023-07-12 08:38 UTC, qkrjh0904 commented on src/main/kotlin/enums/Operator.kt
> +    DIV("/");
Operator에서 연산을 책임지는 것 보다 계산기에서 연산을 책임지는게 맞다고 생각했는데 어떻게 생각하시나요?

2023-07-12 08:38 UTC, qkrjh0904 commented on src/main/kotlin/objects/StringCalculator.kt
> +    private val expression: String?
음.. 생성해두고, 메서드를 호출하는 방식이 더 적합해 보이긴하네요!!

2023-07-12 08:38 UTC, qkrjh0904 commented on src/main/kotlin/objects/StringCalculator.kt
> +        }
좋은 방식인 것 같습니다!
이부분 수정 후에 3 단계에 PR 남기겠습니다.