2단계 - 문자열계산기
lhs0610/kotlin-racingcar pull request #7
Opened 2023-07-11 02:52 UTC by Jong9Developer

2023-07-11 03:02 UTC, lhs0610 requested changes
종욱님 계산기 미션 잘 구현해주셨네요. 
몇 가지 피드백 남겨드렸으니 확인 후 다시 리뷰요청 부탁드려요.

2023-07-11 03:02 UTC, lhs0610 commented on src/test/kotlin/CalculateTest.kt
> +    Given("Calculate") {
Given절인데 무엇인가를 제공하거나 픽스쳐를 제공하지 않는데 BehaviorSpec은 적절한 것 같지가 않네요. DCI나 FunSpec으로도 충분해보입니다

2023-07-11 03:02 UTC, lhs0610 commented on src/test/kotlin/CalculateTest.kt
> +})
0을 대상으로 연산하는 실패 테스트도 있으면 좋을 것 같네요.

2023-07-11 03:02 UTC, lhs0610 commented on src/test/kotlin/CalculateTest.kt
> +    validationNullOrEmpty(formula)
코틀린에는 require,check, assert와 같은 예외를 활용한 제한 블럭을 이용해서 상태 검사를 해줄 수 있습니다.

2023-07-11 03:02 UTC, lhs0610 commented on src/test/kotlin/CalculateTest.kt
> +    val trimFormula = splitByWhiteSpace(formula)
만약 공백이 아닌 별도의 구분자를 이용해 분리를 해야한다면 어떻게 될까요? 이 코드를 수정하면 OCP 원칙을 위배할 수 있습니다. 전략패턴을 이용해 분리자를 추상화 할 수 없을까요?

2023-07-11 03:02 UTC, lhs0610 commented on src/test/kotlin/CalculateTest.kt
> +    var answer = trimFormula[0].toInt()
숫자가 아닌 문자를 대입할 경우에 대한 책임을 어디서 지는게 맞을까요?

2023-07-11 03:02 UTC, lhs0610 commented on src/test/kotlin/CalculateTest.kt
> +    for (i in 1 until trimFormula.size step 2) {
왜 1부터 시작하는지 왜 2씩 증가하는지에 대한 시그니처를 알기 힘들 것 같아요 매직 넘버는 상수로 분리해줘도 좋을 것 같습니다.

2023-07-11 03:02 UTC, lhs0610 commented on src/test/kotlin/CalculateTest.kt
> +private fun calculate(number1: Int, number2: Int, operator: String) =
보통 소트웍스 앤솔러지의 객체지향 8가지 원칙에서는 파라미터를 2개 이상 늘리지 않기를 권장해요. 
실무에서 3개 이상이 되는걸 막는건 사실상 불가능하지만, 해당 미션들은 모두 2개 이내로 처리가 가능하게 만들어졌기에 2개 이하로 줄여볼 수 있을 것 같아요.

2023-07-11 03:02 UTC, lhs0610 commented on src/test/kotlin/CalculateTest.kt
> +        else -> throw IllegalArgumentException()
열거타입을 활용해보면 어떨까요? 
그리고 중위 함수를 활용해본건 좋지만, 이런 사칙연산같은 경우 연산자 오버로딩을 이용해 처리할 수 있습니다. 

그리고 현재는 사칙연산뿐이지만, 추가적인 수식이 추가되는 경우에 대한 유지보수성이 떨어질 수 있어요. 이 경우
열거타입 혹은 sealed class를 활용해서 처리할 수 있는데, 이에 대해 고민해보면 좋을 것 같습니다.

2023-07-11 03:02 UTC, lhs0610 commented on src/test/kotlin/PersonTest.kt
> +                (person1 == person2) shouldBe true
```suggestion
                person1 shouldBe person2
```

이렇게만 해도 될 것 같네요.

data class의 copy 메서드도 테스트해보면 좋을 것 같네요.

2023-07-11 05:42 UTC, Jong9Developer commented on src/test/kotlin/CalculateTest.kt
> +private fun calculate(number1: Int, number2: Int, operator: String) =
2개라면 메서드 분리를 안하는쪽으로 가야겠군용..!

2023-07-19 00:52 UTC, lhs0610 approved these changes
종욱님 문자열 계산기 잘 만들어 주셨어요. 
피드백 남겨드린 부분들이 있으니 확인해주시고 다음 자동차 경주 미션을 진행하시면서 같이 반영해보면 좋을 것 같습니다. 2단계는 여기서 merge하겠습니다.

2023-07-19 00:52 UTC, lhs0610 commented on src/main/kotlin/calculator/enums/Operator.kt
> +enum class Operator(
열거타입 활용 잘 해주셨어요 👍

2023-07-19 00:52 UTC, lhs0610 commented on src/main/kotlin/calculator/enums/Operator.kt
> +        private val SYMBOL_MAP = values().associateBy {
심볼 캐싱 잘 해주셨어요 👍

2023-07-19 00:52 UTC, lhs0610 commented on src/main/kotlin/calculator/utils/CalculatorUtils.kt
> +fun multipleCalculate(formula: String): Double {
개념적 유사성에 따라서 개행을 해주면 코드의 가독성을 높힐 수 있습니다

2023-07-19 00:52 UTC, lhs0610 commented on src/main/kotlin/calculator/utils/StringUtils.kt
> +fun toDouble(str: String): Double =
이 코드가 의미가 있는 코드인지 고민 해 볼 필요가 있어요. 
toDouble이 실패하면 NumberFormatException이라는 명확한 표준 예외가 발생하는데 이를 IllegalArgumentException으로 예외 번역을 해야 할 이유가 있을까요? 한글 메세지를 추가하기 위해서라고 하기엔 그냥 NumberFormatException에 한글 메세지를 추가해도 될 것으로 보이구요. 

try-catch에 드는 비용도 있습니다.

2023-07-19 00:52 UTC, lhs0610 commented on src/main/kotlin/calculator/utils/StringUtils.kt
> +    require(formula != null && formula.isNotBlank()) {
```suggestion
    require(!formula.isNullOrBlank()) {
```
이렇게 작성해줘도 됩니다 ㅎ

2023-07-19 00:52 UTC, lhs0610 commented on src/test/kotlin/CalculateTest.kt
> +            it("덧셈") {
콘솔창에 테스트가 수 백개 이상이 될 경우 콘솔의 이 내용들이 displayName으로 작성될텐데 해당 내용만보고 이게 무슨 테스트인지 알 수 있을까요?

2023-07-19 00:52 UTC, lhs0610 commented on src/main/kotlin/calculator/utils/CalculatorUtils.kt
> +    val trimFormula = splitByWhiteSpace(formula)
기획이 바뀌어서 공백이 아닌 콤마(`,`)나 다른 커스텀 문자열로 분리를 해야 할 경우 어떻게 될까요?

2023-07-19 00:52 UTC, lhs0610 commented on src/main/kotlin/calculator/utils/CalculatorUtils.kt
> +    return answer
좀 더 코틀린스럽게 바꿔보는것도 고민해보면 좋을 것 같아요. 👍

2023-07-19 00:52 UTC, merged

2023-07-20 00:01 UTC, Jong9Developer commented on src/main/kotlin/calculator/utils/CalculatorUtils.kt
> +    val trimFormula = splitByWhiteSpace(formula)
특정 문자열을 직접 받는게 좋겠군요..!